# Generated by Django 5.1.7 on 2026-02-25 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CREATE', 'Creation'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('TOGGLE', 'Activation/Desactivation')], max_length=10, verbose_name='Type')),
                ('target_type', models.CharField(max_length=50, verbose_name='Type de cible')),
                ('target_id', models.CharField(max_length=64, verbose_name='Identifiant cible')),
                ('target_label', models.CharField(max_length=255, verbose_name='Libelle cible')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date action')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL, verbose_name='Administrateur')),
            ],
            options={
                'verbose_name': 'Journal admin',
                'verbose_name_plural': 'Journaux admin',
                'ordering': ['-created_at'],
            },
        ),
    ]
