# Generated by Django 5.1.7 on 2026-02-18 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hopital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'hôpital")),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('contact', models.CharField(max_length=50, verbose_name='Contact / Téléphone')),
                ('code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Code unique')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hôpital',
                'verbose_name_plural': 'Hôpitaux',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Mairie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la mairie')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('contact', models.CharField(max_length=50, verbose_name='Contact / Téléphone')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville / Commune')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mairie',
                'verbose_name_plural': 'Mairies',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='DeclarationNaissance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Référence dossier')),
                ('nom_enfant', models.CharField(max_length=100, verbose_name="Nom de l'enfant")),
                ('prenom_enfant', models.CharField(blank=True, max_length=100, verbose_name="Prénom de l'enfant")),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('heure_naissance', models.TimeField(blank=True, null=True, verbose_name='Heure de naissance')),
                ('lieu_naissance', models.CharField(max_length=200, verbose_name='Lieu de naissance')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('nom_pere', models.CharField(max_length=150, verbose_name='Nom complet du père')),
                ('date_naissance_pere', models.DateField(blank=True, null=True, verbose_name='Date de naissance du père')),
                ('nationalite_pere', models.CharField(blank=True, max_length=100, verbose_name='Nationalité du père')),
                ('profession_pere', models.CharField(blank=True, max_length=100, verbose_name='Profession du père')),
                ('nom_mere', models.CharField(max_length=150, verbose_name='Nom complet de la mère')),
                ('date_naissance_mere', models.DateField(blank=True, null=True, verbose_name='Date de naissance de la mère')),
                ('nationalite_mere', models.CharField(blank=True, max_length=100, verbose_name='Nationalité de la mère')),
                ('profession_mere', models.CharField(blank=True, max_length=100, verbose_name='Profession de la mère')),
                ('email_parents', models.EmailField(blank=True, max_length=254, verbose_name='Email des parents')),
                ('telephone_parents', models.CharField(blank=True, max_length=20, verbose_name='Téléphone des parents')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=15, verbose_name='Statut')),
                ('motif_rejet', models.TextField(blank=True, verbose_name='Motif de rejet')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('agent_hopital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declarations_creees', to=settings.AUTH_USER_MODEL, verbose_name='Agent hôpital')),
                ('agent_mairie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declarations_traitees', to=settings.AUTH_USER_MODEL, verbose_name='Agent mairie')),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='declarations', to='naissances.hopital', verbose_name='Hôpital déclarant')),
                ('mairie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='declarations', to='naissances.mairie', verbose_name='Mairie destinataire')),
            ],
            options={
                'verbose_name': 'Déclaration de naissance',
                'verbose_name_plural': 'Déclarations de naissance',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ActeNaissance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_acte', models.CharField(max_length=30, unique=True, verbose_name="Numéro d'acte")),
                ('date_generation', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='actes_naissance/', verbose_name='Fichier PDF')),
                ('declaration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acte', to='naissances.declarationnaissance', verbose_name='Déclaration associée')),
            ],
            options={
                'verbose_name': 'Acte de naissance',
                'verbose_name_plural': 'Actes de naissance',
                'ordering': ['-date_generation'],
            },
        ),
    ]
