# Generated by Django 5.1.7 on 2026-02-25 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naissances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclarationDeces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Référence dossier')),
                ('nom_defunt', models.CharField(max_length=100, verbose_name='Nom du défunt')),
                ('prenom_defunt', models.CharField(blank=True, max_length=100, verbose_name='Prénom du défunt')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('date_deces', models.DateField(verbose_name='Date du décès')),
                ('lieu_deces', models.CharField(max_length=200, verbose_name='Lieu du décès')),
                ('cause_deces', models.CharField(blank=True, max_length=200, verbose_name='Cause du décès')),
                ('declarant_nom', models.CharField(max_length=150, verbose_name='Nom du déclarant')),
                ('declarant_lien', models.CharField(blank=True, max_length=100, verbose_name='Lien avec le défunt')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('agent_createur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deces_enregistres', to=settings.AUTH_USER_MODEL, verbose_name='Agent déclarant')),
                ('hopital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='declarations_deces', to='naissances.hopital', verbose_name='Hôpital déclarant')),
                ('mairie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='declarations_deces', to='naissances.mairie', verbose_name='Mairie')),
            ],
            options={
                'verbose_name': 'Déclaration de décès',
                'verbose_name_plural': 'Déclarations de décès',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ActeDeces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_acte', models.CharField(max_length=30, unique=True, verbose_name="Numéro d'acte")),
                ('date_generation', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='actes_deces/', verbose_name='Fichier PDF')),
                ('declaration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acte', to='naissances.declarationdeces', verbose_name='Déclaration associée')),
            ],
            options={
                'verbose_name': 'Acte de décès',
                'verbose_name_plural': 'Actes de décès',
                'ordering': ['-date_generation'],
            },
        ),
        migrations.CreateModel(
            name='DeclarationMariage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Référence dossier')),
                ('nom_epoux', models.CharField(max_length=150, verbose_name="Nom complet de l'époux")),
                ('nom_epouse', models.CharField(max_length=150, verbose_name="Nom complet de l'épouse")),
                ('date_naissance_epoux', models.DateField(blank=True, null=True, verbose_name="Date de naissance de l'époux")),
                ('date_naissance_epouse', models.DateField(blank=True, null=True, verbose_name="Date de naissance de l'épouse")),
                ('profession_epoux', models.CharField(blank=True, max_length=100, verbose_name="Profession de l'époux")),
                ('profession_epouse', models.CharField(blank=True, max_length=100, verbose_name="Profession de l'épouse")),
                ('date_mariage', models.DateField(verbose_name='Date du mariage')),
                ('lieu_mariage', models.CharField(max_length=200, verbose_name='Lieu du mariage')),
                ('temoins', models.TextField(blank=True, verbose_name='Témoins')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('agent_mairie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mariages_enregistres', to=settings.AUTH_USER_MODEL, verbose_name='Agent mairie')),
                ('mairie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='declarations_mariage', to='naissances.mairie', verbose_name='Mairie')),
            ],
            options={
                'verbose_name': 'Déclaration de mariage',
                'verbose_name_plural': 'Déclarations de mariage',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ActeMariage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_acte', models.CharField(max_length=30, unique=True, verbose_name="Numéro d'acte")),
                ('date_generation', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='actes_mariage/', verbose_name='Fichier PDF')),
                ('declaration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acte', to='naissances.declarationmariage', verbose_name='Déclaration associée')),
            ],
            options={
                'verbose_name': 'Acte de mariage',
                'verbose_name_plural': 'Actes de mariage',
                'ordering': ['-date_generation'],
            },
        ),
    ]
