# Generated by Django 5.1.7 on 2026-02-25 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naissances', '0002_declarationdeces_actedeces_declarationmariage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='declarationdeces',
            name='agent_traitement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deces_traites', to=settings.AUTH_USER_MODEL, verbose_name='Agent mairie (traitement)'),
        ),
        migrations.AddField(
            model_name='declarationdeces',
            name='date_traitement',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement'),
        ),
        migrations.AddField(
            model_name='declarationdeces',
            name='motif_rejet',
            field=models.TextField(blank=True, verbose_name='Motif de rejet'),
        ),
        migrations.AddField(
            model_name='declarationdeces',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=15, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='declarationmariage',
            name='date_traitement',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement'),
        ),
        migrations.AddField(
            model_name='declarationmariage',
            name='motif_rejet',
            field=models.TextField(blank=True, verbose_name='Motif de rejet'),
        ),
        migrations.AddField(
            model_name='declarationmariage',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=15, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='declarationmariage',
            name='agent_mairie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mariages_enregistres', to=settings.AUTH_USER_MODEL, verbose_name='Agent mairie (traitement)'),
        ),
    ]
