# Generated by Django 5.1.7 on 2026-02-25 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naissances', '0003_declarationdeces_agent_traitement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actedeces',
            options={'ordering': ['-date_generation'], 'verbose_name': 'Acte de deces', 'verbose_name_plural': 'Actes de deces'},
        ),
        migrations.AlterModelOptions(
            name='declarationdeces',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Declaration de deces', 'verbose_name_plural': 'Declarations de deces'},
        ),
        migrations.AlterModelOptions(
            name='declarationmariage',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Declaration de mariage', 'verbose_name_plural': 'Declarations de mariage'},
        ),
        migrations.AlterModelOptions(
            name='declarationnaissance',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Declaration de naissance', 'verbose_name_plural': 'Declarations de naissance'},
        ),
        migrations.AlterModelOptions(
            name='hopital',
            options={'ordering': ['nom'], 'verbose_name': 'Hopital', 'verbose_name_plural': 'Hopitaux'},
        ),
        migrations.AddField(
            model_name='declarationdeces',
            name='date_echeance',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date echeance'),
        ),
        migrations.AddField(
            model_name='declarationdeces',
            name='priorite',
            field=models.CharField(choices=[('NORMALE', 'Normale'), ('URGENTE', 'Urgente')], default='NORMALE', max_length=10, verbose_name='Priorite'),
        ),
        migrations.AddField(
            model_name='declarationmariage',
            name='date_echeance',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date echeance'),
        ),
        migrations.AddField(
            model_name='declarationmariage',
            name='priorite',
            field=models.CharField(choices=[('NORMALE', 'Normale'), ('URGENTE', 'Urgente')], default='NORMALE', max_length=10, verbose_name='Priorite'),
        ),
        migrations.AddField(
            model_name='declarationnaissance',
            name='date_echeance',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date echeance'),
        ),
        migrations.AddField(
            model_name='declarationnaissance',
            name='priorite',
            field=models.CharField(choices=[('NORMALE', 'Normale'), ('URGENTE', 'Urgente')], default='NORMALE', max_length=10, verbose_name='Priorite'),
        ),
        migrations.AlterField(
            model_name='actedeces',
            name='date_generation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de generation'),
        ),
        migrations.AlterField(
            model_name='actedeces',
            name='declaration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acte', to='naissances.declarationdeces', verbose_name='Declaration associee'),
        ),
        migrations.AlterField(
            model_name='actedeces',
            name='numero_acte',
            field=models.CharField(max_length=30, unique=True, verbose_name="Numero d'acte"),
        ),
        migrations.AlterField(
            model_name='actemariage',
            name='date_generation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de generation'),
        ),
        migrations.AlterField(
            model_name='actemariage',
            name='declaration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acte', to='naissances.declarationmariage', verbose_name='Declaration associee'),
        ),
        migrations.AlterField(
            model_name='actemariage',
            name='numero_acte',
            field=models.CharField(max_length=30, unique=True, verbose_name="Numero d'acte"),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='date_generation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de generation'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='declaration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acte', to='naissances.declarationnaissance', verbose_name='Declaration associee'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='numero_acte',
            field=models.CharField(max_length=30, unique=True, verbose_name="Numero d'acte"),
        ),
        migrations.AlterField(
            model_name='declarationdeces',
            name='agent_createur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deces_enregistres', to=settings.AUTH_USER_MODEL, verbose_name='Agent declarant'),
        ),
        migrations.AlterField(
            model_name='declarationdeces',
            name='cause_deces',
            field=models.CharField(blank=True, max_length=200, verbose_name='Cause du deces'),
        ),
        migrations.AlterField(
            model_name='declarationdeces',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de creation'),
        ),
        migrations.AlterField(
            model_name='declarationdeces',
            name='date_deces',
            field=models.DateField(verbose_name='Date du deces'),
        ),
        migrations.AlterField(
            model_name='declarationdeces',
            name='declarant_lien',
            field=models.CharField(blank=True, max_length=100, verbose_name='Lien avec le defunt'),
        ),
        migrations.AlterField(
            model_name='declarationdeces',
            name='declarant_nom',
            field=models.CharField(max_length=150, verbose_name='Nom du declarant'),
        ),
        migrations.AlterField(
            model_name='declarationdeces',
            name='hopital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='declarations_deces', to='naissances.hopital', verbose_name='Hopital declarant'),
        ),
        migrations.AlterField(
            model_name='declarationdeces',
            name='lieu_deces',
            field=models.CharField(max_length=200, verbose_name='Lieu du deces'),
        ),
        migrations.AlterField(
            model_name='declarationdeces',
            name='nom_defunt',
            field=models.CharField(max_length=100, verbose_name='Nom du defunt'),
        ),
        migrations.AlterField(
            model_name='declarationdeces',
            name='prenom_defunt',
            field=models.CharField(blank=True, max_length=100, verbose_name='Prenom du defunt'),
        ),
        migrations.AlterField(
            model_name='declarationdeces',
            name='reference',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Reference dossier'),
        ),
        migrations.AlterField(
            model_name='declarationdeces',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1, verbose_name='Sexe'),
        ),
        migrations.AlterField(
            model_name='declarationdeces',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_VERIFICATION', 'En verification'), ('VALIDE', 'Valide'), ('REJETE', 'Rejete')], default='EN_ATTENTE', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='declarationmariage',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de creation'),
        ),
        migrations.AlterField(
            model_name='declarationmariage',
            name='date_naissance_epouse',
            field=models.DateField(blank=True, null=True, verbose_name="Date de naissance de l'epouse"),
        ),
        migrations.AlterField(
            model_name='declarationmariage',
            name='date_naissance_epoux',
            field=models.DateField(blank=True, null=True, verbose_name="Date de naissance de l'epoux"),
        ),
        migrations.AlterField(
            model_name='declarationmariage',
            name='nom_epouse',
            field=models.CharField(max_length=150, verbose_name="Nom complet de l'epouse"),
        ),
        migrations.AlterField(
            model_name='declarationmariage',
            name='nom_epoux',
            field=models.CharField(max_length=150, verbose_name="Nom complet de l'epoux"),
        ),
        migrations.AlterField(
            model_name='declarationmariage',
            name='profession_epouse',
            field=models.CharField(blank=True, max_length=100, verbose_name="Profession de l'epouse"),
        ),
        migrations.AlterField(
            model_name='declarationmariage',
            name='profession_epoux',
            field=models.CharField(blank=True, max_length=100, verbose_name="Profession de l'epoux"),
        ),
        migrations.AlterField(
            model_name='declarationmariage',
            name='reference',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Reference dossier'),
        ),
        migrations.AlterField(
            model_name='declarationmariage',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_VERIFICATION', 'En verification'), ('VALIDE', 'Valide'), ('REJETE', 'Rejete')], default='EN_ATTENTE', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='declarationmariage',
            name='temoins',
            field=models.TextField(blank=True, verbose_name='Temoins'),
        ),
        migrations.AlterField(
            model_name='declarationnaissance',
            name='agent_hopital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declarations_creees', to=settings.AUTH_USER_MODEL, verbose_name='Agent hopital'),
        ),
        migrations.AlterField(
            model_name='declarationnaissance',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de creation'),
        ),
        migrations.AlterField(
            model_name='declarationnaissance',
            name='date_naissance_mere',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance de la mere'),
        ),
        migrations.AlterField(
            model_name='declarationnaissance',
            name='date_naissance_pere',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance du pere'),
        ),
        migrations.AlterField(
            model_name='declarationnaissance',
            name='hopital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='declarations', to='naissances.hopital', verbose_name='Hopital declarant'),
        ),
        migrations.AlterField(
            model_name='declarationnaissance',
            name='nationalite_mere',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nationalite de la mere'),
        ),
        migrations.AlterField(
            model_name='declarationnaissance',
            name='nationalite_pere',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nationalite du pere'),
        ),
        migrations.AlterField(
            model_name='declarationnaissance',
            name='nom_mere',
            field=models.CharField(max_length=150, verbose_name='Nom complet de la mere'),
        ),
        migrations.AlterField(
            model_name='declarationnaissance',
            name='nom_pere',
            field=models.CharField(max_length=150, verbose_name='Nom complet du pere'),
        ),
        migrations.AlterField(
            model_name='declarationnaissance',
            name='prenom_enfant',
            field=models.CharField(blank=True, max_length=100, verbose_name="Prenom de l'enfant"),
        ),
        migrations.AlterField(
            model_name='declarationnaissance',
            name='profession_mere',
            field=models.CharField(blank=True, max_length=100, verbose_name='Profession de la mere'),
        ),
        migrations.AlterField(
            model_name='declarationnaissance',
            name='profession_pere',
            field=models.CharField(blank=True, max_length=100, verbose_name='Profession du pere'),
        ),
        migrations.AlterField(
            model_name='declarationnaissance',
            name='reference',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Reference dossier'),
        ),
        migrations.AlterField(
            model_name='declarationnaissance',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1, verbose_name='Sexe'),
        ),
        migrations.AlterField(
            model_name='declarationnaissance',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_VERIFICATION', 'En verification'), ('VALIDE', 'Valide'), ('REJETE', 'Rejete')], default='EN_ATTENTE', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='declarationnaissance',
            name='telephone_parents',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telephone des parents'),
        ),
        migrations.AlterField(
            model_name='hopital',
            name='contact',
            field=models.CharField(max_length=50, verbose_name='Contact / Telephone'),
        ),
        migrations.AlterField(
            model_name='hopital',
            name='nom',
            field=models.CharField(max_length=200, verbose_name="Nom de l'hopital"),
        ),
        migrations.AlterField(
            model_name='mairie',
            name='contact',
            field=models.CharField(max_length=50, verbose_name='Contact / Telephone'),
        ),
        migrations.CreateModel(
            name='HistoriqueDeces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('statut_avant', models.CharField(blank=True, max_length=20)),
                ('statut_apres', models.CharField(blank=True, max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='naissances.declarationdeces')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueMariage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('statut_avant', models.CharField(blank=True, max_length=20)),
                ('statut_apres', models.CharField(blank=True, max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='naissances.declarationmariage')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueNaissance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('statut_avant', models.CharField(blank=True, max_length=20)),
                ('statut_apres', models.CharField(blank=True, max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='naissances.declarationnaissance')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_action'],
            },
        ),
    ]
