# Generated by Django 5.1.7 on 2026-02-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naissances', '0004_alter_actedeces_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='declarationnaissance',
            index=models.Index(fields=['mairie', 'statut'], name='dn_mairie_statut_idx'),
        ),
        migrations.AddIndex(
            model_name='declarationnaissance',
            index=models.Index(fields=['hopital', 'statut'], name='dn_hopital_statut_idx'),
        ),
        migrations.AddIndex(
            model_name='declarationnaissance',
            index=models.Index(fields=['date_creation'], name='dn_date_creation_idx'),
        ),
        migrations.AddIndex(
            model_name='declarationnaissance',
            index=models.Index(fields=['date_echeance'], name='dn_date_echeance_idx'),
        ),
        migrations.AddConstraint(
            model_name='declarationnaissance',
            constraint=models.CheckConstraint(
                condition=models.Q(date_naissance_pere__isnull=True) | models.Q(date_naissance_pere__lt=models.F('date_naissance')),
                name='dn_pere_before_naissance',
            ),
        ),
        migrations.AddConstraint(
            model_name='declarationnaissance',
            constraint=models.CheckConstraint(
                condition=models.Q(date_naissance_mere__isnull=True) | models.Q(date_naissance_mere__lt=models.F('date_naissance')),
                name='dn_mere_before_naissance',
            ),
        ),
        migrations.AddIndex(
            model_name='declarationmariage',
            index=models.Index(fields=['mairie', 'statut'], name='dm_mairie_statut_idx'),
        ),
        migrations.AddIndex(
            model_name='declarationmariage',
            index=models.Index(fields=['date_creation'], name='dm_date_creation_idx'),
        ),
        migrations.AddIndex(
            model_name='declarationmariage',
            index=models.Index(fields=['date_echeance'], name='dm_date_echeance_idx'),
        ),
        migrations.AddConstraint(
            model_name='declarationmariage',
            constraint=models.CheckConstraint(
                condition=models.Q(date_naissance_epoux__isnull=True) | models.Q(date_naissance_epoux__lt=models.F('date_mariage')),
                name='dm_epoux_before_mariage',
            ),
        ),
        migrations.AddConstraint(
            model_name='declarationmariage',
            constraint=models.CheckConstraint(
                condition=models.Q(date_naissance_epouse__isnull=True) | models.Q(date_naissance_epouse__lt=models.F('date_mariage')),
                name='dm_epouse_before_mariage',
            ),
        ),
        migrations.AddIndex(
            model_name='declarationdeces',
            index=models.Index(fields=['mairie', 'statut'], name='dd_mairie_statut_idx'),
        ),
        migrations.AddIndex(
            model_name='declarationdeces',
            index=models.Index(fields=['hopital', 'statut'], name='dd_hopital_statut_idx'),
        ),
        migrations.AddIndex(
            model_name='declarationdeces',
            index=models.Index(fields=['date_creation'], name='dd_date_creation_idx'),
        ),
        migrations.AddIndex(
            model_name='declarationdeces',
            index=models.Index(fields=['date_echeance'], name='dd_date_echeance_idx'),
        ),
        migrations.AddConstraint(
            model_name='declarationdeces',
            constraint=models.CheckConstraint(
                condition=models.Q(date_naissance__isnull=True) | models.Q(date_naissance__lte=models.F('date_deces')),
                name='dd_birth_before_death',
            ),
        ),
    ]
