# Generated by Django 5.1.7 on 2026-02-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naissances', '0005_declaration_indexes_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='declarationmariage',
            name='email_contact',
            field=models.EmailField(blank=True, verbose_name='Email de contact (epoux/epouse)'),
        ),
        migrations.AddField(
            model_name='declarationdeces',
            name='email_contact',
            field=models.EmailField(blank=True, verbose_name='Email de contact du declarant'),
        ),
    ]
